using System;

namespace Buckle.CodeAnalysis.Binding;

[Flags]
internal enum BinaryOperatorKind : int {
    Error = 0x00000000,

    TypeMask = UnaryOperatorKind.TypeMask,

    Int = UnaryOperatorKind.Int,
    UInt = UnaryOperatorKind.UInt,
    Char = UnaryOperatorKind.Char,
    Float32 = UnaryOperatorKind.Float32,
    Float64 = UnaryOperatorKind.Float64,
    Bool = UnaryOperatorKind.Bool,
    Object = UnaryOperatorKind._Object,
    String = UnaryOperatorKind._String,
    Type = UnaryOperatorKind._Type,
    NullableNull = UnaryOperatorKind._NullableNull,
    Any = UnaryOperatorKind.Any,
    UserDefined = UnaryOperatorKind.UserDefined,

    OpMask = UnaryOperatorKind.OpMask,

    Multiplication = 0x00001000,
    Addition = 0x00001100,
    Subtraction = 0x00001200,
    Division = 0x00001300,
    Modulo = 0x00001400,
    LeftShift = 0x00001500,
    RightShift = 0x00001600,
    Equal = 0x00001700,
    NotEqual = 0x00001800,
    GreaterThan = 0x00001900,
    LessThan = 0x00001A00,
    GreaterThanOrEqual = 0x00001B00,
    LessThanOrEqual = 0x00001C00,
    UnsignedRightShift = 0x00001D00,
    And = 0x00001E00,
    Or = 0x00001F00,
    Xor = 0x00002000,
    Power = 0x00002100,

    Conditional = UnaryOperatorKind._Conditional,
    Lifted = UnaryOperatorKind.Lifted,

    IntMultiplication = Int | Multiplication,
    UIntMultiplication = UInt | Multiplication,
    Float32Multiplication = Float32 | Multiplication,
    Float64Multiplication = Float64 | Multiplication,
    UserDefinedMultiplication = UserDefined | Multiplication,
    LiftedUIntMultiplication = Lifted | UInt | Multiplication,
    LiftedIntMultiplication = Lifted | Int | Multiplication,
    LiftedFloat32Multiplication = Lifted | Float32 | Multiplication,
    LiftedFloat64Multiplication = Lifted | Float64 | Multiplication,
    LiftedUserDefinedMultiplication = Lifted | UserDefined | Multiplication,

    IntAddition = Int | Addition,
    UIntAddition = UInt | Addition,
    Float32Addition = Float32 | Addition,
    Float64Addition = Float64 | Addition,
    StringConcatenation = String | Addition,
    UserDefinedAddition = UserDefined | Addition,
    LiftedIntAddition = Lifted | Int | Addition,
    LiftedUIntAddition = Lifted | UInt | Addition,
    LiftedFloat32Addition = Lifted | Float32 | Addition,
    LiftedFloat64Addition = Lifted | Float64 | Addition,
    LiftedStringConcatenation = Lifted | String | Addition,
    LiftedUserDefinedAddition = Lifted | UserDefined | Addition,

    IntSubtraction = Int | Subtraction,
    UIntSubtraction = UInt | Subtraction,
    Float32Subtraction = Float32 | Subtraction,
    Float64Subtraction = Float64 | Subtraction,
    UserDefinedSubtraction = UserDefined | Subtraction,
    LiftedIntSubtraction = Lifted | Int | Subtraction,
    LiftedUIntSubtraction = Lifted | UInt | Subtraction,
    LiftedFloat32Subtraction = Lifted | Float32 | Subtraction,
    LiftedFloat64Subtraction = Lifted | Float64 | Subtraction,
    LiftedUserDefinedSubtraction = Lifted | UserDefined | Subtraction,

    IntDivision = Int | Division,
    UIntDivision = UInt | Division,
    Float32Division = Float32 | Division,
    Float64Division = Float64 | Division,
    UserDefinedDivision = UserDefined | Division,
    LiftedIntDivision = Lifted | Int | Division,
    LiftedUIntDivision = Lifted | UInt | Division,
    LiftedFloat32Division = Lifted | Float32 | Division,
    LiftedFloat64Division = Lifted | Float64 | Division,
    LiftedUserDefinedDivision = Lifted | UserDefined | Division,

    IntModulo = Int | Modulo,
    UIntModulo = UInt | Modulo,
    Float32Modulo = Float32 | Modulo,
    Float64Modulo = Float64 | Modulo,
    UserDefinedModulo = UserDefined | Modulo,
    LiftedIntModulo = Lifted | Int | Modulo,
    LiftedUIntModulo = Lifted | UInt | Modulo,
    LiftedFloat32Modulo = Lifted | Float32 | Modulo,
    LiftedFloat64Modulo = Lifted | Float64 | Modulo,
    LiftedUserDefinedModulo = Lifted | UserDefined | Modulo,

    IntLeftShift = Int | LeftShift,
    UIntLeftShift = UInt | LeftShift,
    UserDefinedLeftShift = UserDefined | LeftShift,
    LiftedIntLeftShift = Lifted | Int | LeftShift,
    LiftedUIntLeftShift = Lifted | UInt | LeftShift,
    LiftedUserDefinedLeftShift = Lifted | UserDefined | LeftShift,

    IntRightShift = Int | RightShift,
    UIntRightShift = UInt | RightShift,
    UserDefinedRightShift = UserDefined | RightShift,
    LiftedIntRightShift = Lifted | Int | RightShift,
    LiftedUIntRightShift = Lifted | UInt | RightShift,
    LiftedUserDefinedRightShift = Lifted | UserDefined | RightShift,

    IntUnsignedRightShift = Int | UnsignedRightShift,
    UIntUnsignedRightShift = UInt | UnsignedRightShift,
    UserDefinedUnsignedRightShift = UserDefined | UnsignedRightShift,
    LiftedIntUnsignedRightShift = Lifted | Int | UnsignedRightShift,
    LiftedUIntUnsignedRightShift = Lifted | UInt | UnsignedRightShift,
    LiftedUserDefinedUnsignedRightShift = Lifted | UserDefined | UnsignedRightShift,

    IntEqual = Int | Equal,
    UIntEqual = UInt | Equal,
    Float32Equal = Float32 | Equal,
    Float64Equal = Float64 | Equal,
    BoolEqual = Bool | Equal,
    CharEqual = Char | Equal,
    NullableNullEqual = NullableNull | Equal,
    UserDefinedEqual = UserDefined | Equal,
    StringEqual = String | Equal,
    ObjectEqual = Object | Equal,
    TypeEqual = Type | Equal,
    LiftedIntEqual = Lifted | Int | Equal,
    LiftedUIntEqual = Lifted | UInt | Equal,
    LiftedFloat32Equal = Lifted | Float32 | Equal,
    LiftedFloat64Equal = Lifted | Float64 | Equal,
    LiftedBoolEqual = Lifted | Bool | Equal,
    LiftedCharEqual = Lifted | Char | Equal,
    LiftedNullableNullEqual = Lifted | NullableNull | Equal,
    LiftedUserDefinedEqual = Lifted | UserDefined | Equal,
    LiftedStringEqual = Lifted | String | Equal,
    LiftedObjectEqual = Lifted | Object | Equal,
    LiftedTypeEqual = Lifted | Type | Equal,

    IntNotEqual = Int | NotEqual,
    UIntNotEqual = UInt | NotEqual,
    Float32NotEqual = Float32 | NotEqual,
    Float64NotEqual = Float64 | NotEqual,
    BoolNotEqual = Bool | NotEqual,
    CharNotEqual = Char | NotEqual,
    NullableNullNotEqual = NullableNull | NotEqual,
    UserDefinedNotEqual = UserDefined | NotEqual,
    StringNotEqual = String | NotEqual,
    ObjectNotEqual = Object | NotEqual,
    TypeNotEqual = Type | NotEqual,
    LiftedIntNotEqual = Lifted | Int | NotEqual,
    LiftedUIntNotEqual = Lifted | UInt | NotEqual,
    LiftedFloat32NotEqual = Lifted | Float32 | NotEqual,
    LiftedFloat64NotEqual = Lifted | Float64 | NotEqual,
    LiftedBoolNotEqual = Lifted | Bool | NotEqual,
    LiftedCharNotEqual = Lifted | Char | NotEqual,
    LiftedNullableNullNotEqual = Lifted | NullableNull | NotEqual,
    LiftedUserDefinedNotEqual = Lifted | UserDefined | NotEqual,
    LiftedStringNotEqual = Lifted | String | NotEqual,
    LiftedObjectNotEqual = Lifted | Object | NotEqual,
    LiftedTypeNotEqual = Lifted | Type | NotEqual,

    IntLessThan = Int | LessThan,
    UIntLessThan = UInt | LessThan,
    Float32LessThan = Float32 | LessThan,
    Float64LessThan = Float64 | LessThan,
    UserDefinedLessThan = UserDefined | LessThan,
    LiftedIntLessThan = Lifted | Int | LessThan,
    LiftedUIntLessThan = Lifted | UInt | LessThan,
    LiftedFloat32LessThan = Lifted | Float32 | LessThan,
    LiftedFloat64LessThan = Lifted | Float64 | LessThan,
    LiftedUserDefinedLessThan = Lifted | UserDefined | LessThan,

    IntGreaterThan = Int | GreaterThan,
    UIntGreaterThan = UInt | GreaterThan,
    Float32GreaterThan = Float32 | GreaterThan,
    Float64GreaterThan = Float64 | GreaterThan,
    UserDefinedGreaterThan = UserDefined | GreaterThan,
    LiftedIntGreaterThan = Lifted | Int | GreaterThan,
    LiftedUIntGreaterThan = Lifted | UInt | GreaterThan,
    LiftedFloat32GreaterThan = Lifted | Float32 | GreaterThan,
    LiftedFloat64GreaterThan = Lifted | Float64 | GreaterThan,
    LiftedUserDefinedGreaterThan = Lifted | UserDefined | GreaterThan,

    IntLessThanOrEqual = Int | LessThanOrEqual,
    UIntLessThanOrEqual = UInt | LessThanOrEqual,
    Float32LessThanOrEqual = Float32 | LessThanOrEqual,
    Float64LessThanOrEqual = Float64 | LessThanOrEqual,
    UserDefinedLessThanOrEqual = UserDefined | LessThanOrEqual,
    LiftedIntLessThanOrEqual = Lifted | Int | LessThanOrEqual,
    LiftedUIntLessThanOrEqual = Lifted | UInt | LessThanOrEqual,
    LiftedFloat32LessThanOrEqual = Lifted | Float32 | LessThanOrEqual,
    LiftedFloat64LessThanOrEqual = Lifted | Float64 | LessThanOrEqual,
    LiftedUserDefinedLessThanOrEqual = Lifted | UserDefined | LessThanOrEqual,

    IntGreaterThanOrEqual = Int | GreaterThanOrEqual,
    UIntGreaterThanOrEqual = UInt | GreaterThanOrEqual,
    Float32GreaterThanOrEqual = Float32 | GreaterThanOrEqual,
    Float64GreaterThanOrEqual = Float64 | GreaterThanOrEqual,
    UserDefinedGreaterThanOrEqual = UserDefined | GreaterThanOrEqual,
    LiftedIntGreaterThanOrEqual = Lifted | Int | GreaterThanOrEqual,
    LiftedUIntGreaterThanOrEqual = Lifted | UInt | GreaterThanOrEqual,
    LiftedFloat32GreaterThanOrEqual = Lifted | Float32 | GreaterThanOrEqual,
    LiftedFloat64GreaterThanOrEqual = Lifted | Float64 | GreaterThanOrEqual,
    LiftedUserDefinedGreaterThanOrEqual = Lifted | UserDefined | GreaterThanOrEqual,

    IntAnd = Int | And,
    UIntAnd = UInt | And,
    BoolAnd = Bool | And,
    UserDefinedAnd = UserDefined | And,
    LiftedIntAnd = Lifted | Int | And,
    LiftedUIntAnd = Lifted | UInt | And,
    LiftedBoolAnd = Lifted | Bool | And,
    LiftedUserDefinedAnd = Lifted | UserDefined | And,

    ConditionalAnd = And | Conditional,
    BoolConditionalAnd = Bool | ConditionalAnd,
    UserDefinedConditionalAnd = UserDefined | ConditionalAnd,
    LiftedConditionalAnd = Lifted | And | Conditional,
    LiftedBoolConditionalAnd = Lifted | Bool | ConditionalAnd,
    LiftedUserDefinedConditionalAnd = Lifted | UserDefined | ConditionalAnd,

    IntOr = Int | Or,
    UIntOr = UInt | Or,
    BoolOr = Bool | Or,
    UserDefinedOr = UserDefined | Or,
    LiftedIntOr = Lifted | Int | Or,
    LiftedUIntOr = Lifted | UInt | Or,
    LiftedBoolOr = Lifted | Bool | Or,
    LiftedUserDefinedOr = Lifted | UserDefined | Or,

    ConditionalOr = Or | Conditional,
    BoolConditionalOr = Bool | ConditionalOr,
    UserDefinedConditionalOr = UserDefined | ConditionalOr,
    LiftedConditionalOr = Lifted | Or | Conditional,
    LiftedBoolConditionalOr = Lifted | Bool | ConditionalOr,
    LiftedUserDefinedConditionalOr = Lifted | UserDefined | ConditionalOr,

    IntXor = Int | Xor,
    UIntXor = UInt | Xor,
    BoolXor = Bool | Xor,
    UserDefinedXor = UserDefined | Xor,
    LiftedIntXor = Lifted | Int | Xor,
    LiftedUIntXor = Lifted | UInt | Xor,
    LiftedBoolXor = Lifted | Bool | Xor,
    LiftedUserDefinedXor = Lifted | UserDefined | Xor,

    IntPower = Int | Power,
    UIntPower = UInt | Power,
    Float32Power = Float32 | Power,
    Float64Power = Float64 | Power,
    UserDefinedPower = UserDefined | Power,
    LiftedIntPower = Lifted | Int | Power,
    LiftedUIntPower = Lifted | UInt | Power,
    LiftedFloat32Power = Lifted | Float32 | Power,
    LiftedFloat64Power = Lifted | Float64 | Power,
    LiftedUserDefinedPower = Lifted | UserDefined | Power,
}
