using System;

namespace Buckle.CodeAnalysis.Binding;

[Flags]
internal enum BinaryOperatorKind : int {
    Error = 0x00000000,

    TypeMask = UnaryOperatorKind.TypeMask,

    Int = UnaryOperatorKind.Int,
    Char = UnaryOperatorKind.Char,
    Decimal = UnaryOperatorKind.Decimal,
    Bool = UnaryOperatorKind.Bool,
    Object = UnaryOperatorKind._Object,
    String = UnaryOperatorKind._String,
    Type = UnaryOperatorKind._Type,
    NullableNull = UnaryOperatorKind._NullableNull,
    Any = UnaryOperatorKind.Any,
    UserDefined = UnaryOperatorKind.UserDefined,

    OpMask = UnaryOperatorKind.OpMask,

    Multiplication = 0x00001000,
    Addition = 0x00001100,
    Subtraction = 0x00001200,
    Division = 0x00001300,
    Modulo = 0x00001400,
    LeftShift = 0x00001500,
    RightShift = 0x00001600,
    Equal = 0x00001700,
    NotEqual = 0x00001800,
    GreaterThan = 0x00001900,
    LessThan = 0x00001A00,
    GreaterThanOrEqual = 0x00001B00,
    LessThanOrEqual = 0x00001C00,
    UnsignedRightShift = 0x00001D00,
    And = 0x00001E00,
    Or = 0x00001F00,
    Xor = 0x00002000,
    Power = 0x00002100,

    Conditional = UnaryOperatorKind._Conditional,
    Lifted = UnaryOperatorKind.Lifted,

    IntMultiplication = Int | Multiplication,
    DecimalMultiplication = Decimal | Multiplication,
    UserDefinedMultiplication = UserDefined | Multiplication,
    LiftedIntMultiplication = Lifted | Int | Multiplication,
    LiftedDecimalMultiplication = Lifted | Decimal | Multiplication,
    LiftedUserDefinedMultiplication = Lifted | UserDefined | Multiplication,

    IntAddition = Int | Addition,
    DecimalAddition = Decimal | Addition,
    StringConcatenation = String | Addition,
    UserDefinedAddition = UserDefined | Addition,
    LiftedIntAddition = Lifted | Int | Addition,
    LiftedDecimalAddition = Lifted | Decimal | Addition,
    LiftedStringConcatenation = Lifted | String | Addition,
    LiftedUserDefinedAddition = Lifted | UserDefined | Addition,

    IntSubtraction = Int | Subtraction,
    DecimalSubtraction = Decimal | Subtraction,
    UserDefinedSubtraction = UserDefined | Subtraction,
    LiftedIntSubtraction = Lifted | Int | Subtraction,
    LiftedDecimalSubtraction = Lifted | Decimal | Subtraction,
    LiftedUserDefinedSubtraction = Lifted | UserDefined | Subtraction,

    IntDivision = Int | Division,
    DecimalDivision = Decimal | Division,
    UserDefinedDivision = UserDefined | Division,
    LiftedIntDivision = Lifted | Int | Division,
    LiftedDecimalDivision = Lifted | Decimal | Division,
    LiftedUserDefinedDivision = Lifted | UserDefined | Division,

    IntModulo = Int | Modulo,
    DecimalModulo = Decimal | Modulo,
    UserDefinedModulo = UserDefined | Modulo,
    LiftedIntModulo = Lifted | Int | Modulo,
    LiftedDecimalModulo = Lifted | Decimal | Modulo,
    LiftedUserDefinedModulo = Lifted | UserDefined | Modulo,

    IntLeftShift = Int | LeftShift,
    UserDefinedLeftShift = UserDefined | LeftShift,
    LiftedIntLeftShift = Lifted | Int | LeftShift,
    LiftedUserDefinedLeftShift = Lifted | UserDefined | LeftShift,

    IntRightShift = Int | RightShift,
    UserDefinedRightShift = UserDefined | RightShift,
    LiftedIntRightShift = Lifted | Int | RightShift,
    LiftedUserDefinedRightShift = Lifted | UserDefined | RightShift,

    IntUnsignedRightShift = Int | UnsignedRightShift,
    UserDefinedUnsignedRightShift = UserDefined | UnsignedRightShift,
    LiftedIntUnsignedRightShift = Lifted | Int | UnsignedRightShift,
    LiftedUserDefinedUnsignedRightShift = Lifted | UserDefined | UnsignedRightShift,

    IntEqual = Int | Equal,
    DecimalEqual = Decimal | Equal,
    BoolEqual = Bool | Equal,
    CharEqual = Char | Equal,
    NullableNullEqual = NullableNull | Equal,
    UserDefinedEqual = UserDefined | Equal,
    StringEqual = String | Equal,
    ObjectEqual = Object | Equal,
    TypeEqual = Type | Equal,
    LiftedIntEqual = Lifted | Int | Equal,
    LiftedDecimalEqual = Lifted | Decimal | Equal,
    LiftedBoolEqual = Lifted | Bool | Equal,
    LiftedCharEqual = Lifted | Char | Equal,
    LiftedNullableNullEqual = Lifted | NullableNull | Equal,
    LiftedUserDefinedEqual = Lifted | UserDefined | Equal,
    LiftedStringEqual = Lifted | String | Equal,
    LiftedObjectEqual = Lifted | Object | Equal,
    LiftedTypeEqual = Lifted | Type | Equal,

    IntNotEqual = Int | NotEqual,
    DecimalNotEqual = Decimal | NotEqual,
    BoolNotEqual = Bool | NotEqual,
    CharNotEqual = Char | NotEqual,
    NullableNullNotEqual = NullableNull | NotEqual,
    UserDefinedNotEqual = UserDefined | NotEqual,
    StringNotEqual = String | NotEqual,
    ObjectNotEqual = Object | NotEqual,
    TypeNotEqual = Type | NotEqual,
    LiftedIntNotEqual = Lifted | Int | NotEqual,
    LiftedDecimalNotEqual = Lifted | Decimal | NotEqual,
    LiftedBoolNotEqual = Lifted | Bool | NotEqual,
    LiftedCharNotEqual = Lifted | Char | NotEqual,
    LiftedNullableNullNotEqual = Lifted | NullableNull | NotEqual,
    LiftedUserDefinedNotEqual = Lifted | UserDefined | NotEqual,
    LiftedStringNotEqual = Lifted | String | NotEqual,
    LiftedObjectNotEqual = Lifted | Object | NotEqual,
    LiftedTypeNotEqual = Lifted | Type | NotEqual,

    IntLessThan = Int | LessThan,
    DecimalLessThan = Decimal | LessThan,
    UserDefinedLessThan = UserDefined | LessThan,
    LiftedIntLessThan = Lifted | Int | LessThan,
    LiftedDecimalLessThan = Lifted | Decimal | LessThan,
    LiftedUserDefinedLessThan = Lifted | UserDefined | LessThan,

    IntGreaterThan = Int | GreaterThan,
    DecimalGreaterThan = Decimal | GreaterThan,
    UserDefinedGreaterThan = UserDefined | GreaterThan,
    LiftedIntGreaterThan = Lifted | Int | GreaterThan,
    LiftedDecimalGreaterThan = Lifted | Decimal | GreaterThan,
    LiftedUserDefinedGreaterThan = Lifted | UserDefined | GreaterThan,

    IntLessThanOrEqual = Int | LessThanOrEqual,
    DecimalLessThanOrEqual = Decimal | LessThanOrEqual,
    UserDefinedLessThanOrEqual = UserDefined | LessThanOrEqual,
    LiftedIntLessThanOrEqual = Lifted | Int | LessThanOrEqual,
    LiftedDecimalLessThanOrEqual = Lifted | Decimal | LessThanOrEqual,
    LiftedUserDefinedLessThanOrEqual = Lifted | UserDefined | LessThanOrEqual,

    IntGreaterThanOrEqual = Int | GreaterThanOrEqual,
    DecimalGreaterThanOrEqual = Decimal | GreaterThanOrEqual,
    UserDefinedGreaterThanOrEqual = UserDefined | GreaterThanOrEqual,
    LiftedIntGreaterThanOrEqual = Lifted | Int | GreaterThanOrEqual,
    LiftedDecimalGreaterThanOrEqual = Lifted | Decimal | GreaterThanOrEqual,
    LiftedUserDefinedGreaterThanOrEqual = Lifted | UserDefined | GreaterThanOrEqual,

    IntAnd = Int | And,
    BoolAnd = Bool | And,
    UserDefinedAnd = UserDefined | And,
    LiftedIntAnd = Lifted | Int | And,
    LiftedBoolAnd = Lifted | Bool | And,
    LiftedUserDefinedAnd = Lifted | UserDefined | And,

    ConditionalAnd = And | Conditional,
    BoolConditionalAnd = Bool | ConditionalAnd,
    UserDefinedConditionalAnd = UserDefined | ConditionalAnd,
    LiftedConditionalAnd = Lifted | And | Conditional,
    LiftedBoolConditionalAnd = Lifted | Bool | ConditionalAnd,
    LiftedUserDefinedConditionalAnd = Lifted | UserDefined | ConditionalAnd,

    IntOr = Int | Or,
    BoolOr = Bool | Or,
    UserDefinedOr = UserDefined | Or,
    LiftedIntOr = Lifted | Int | Or,
    LiftedBoolOr = Lifted | Bool | Or,
    LiftedUserDefinedOr = Lifted | UserDefined | Or,

    ConditionalOr = Or | Conditional,
    BoolConditionalOr = Bool | ConditionalOr,
    UserDefinedConditionalOr = UserDefined | ConditionalOr,
    LiftedConditionalOr = Lifted | Or | Conditional,
    LiftedBoolConditionalOr = Lifted | Bool | ConditionalOr,
    LiftedUserDefinedConditionalOr = Lifted | UserDefined | ConditionalOr,

    IntXor = Int | Xor,
    BoolXor = Bool | Xor,
    UserDefinedXor = UserDefined | Xor,
    LiftedIntXor = Lifted | Int | Xor,
    LiftedBoolXor = Lifted | Bool | Xor,
    LiftedUserDefinedXor = Lifted | UserDefined | Xor,

    IntPower = Int | Power,
    DecimalPower = Decimal | Power,
    UserDefinedPower = UserDefined | Power,
    LiftedIntPower = Lifted | Int | Power,
    LiftedDecimalPower = Lifted | Decimal | Power,
    LiftedUserDefinedPower = Lifted | UserDefined | Power,
}
