using System;

namespace Buckle.CodeAnalysis.Binding;

[Flags]
internal enum UnaryOperatorKind : int {
    Error = 0x00000000,

    TypeMask = 0x000000FF,

    Int8 = 0x00000001,
    UInt8 = 0x00000002,
    Int16 = 0x00000003,
    UInt16 = 0x00000004,
    Int32 = 0x00000005,
    UInt32 = 0x00000006,
    Int64 = 0x00000007,
    UInt64 = 0x00000008,
    Char = 0x00000009,
    Float32 = 0x0000000A,
    Float64 = 0x0000000B,
    Bool = 0x0000000C,
    _Object = 0x0000000D,
    _String = 0x0000000E,
    _Type = 0x0000000F,
    _NullableNull = 0x00000010,
    Any = 0x00000011,
    UserDefined = 0x00000012,
    Enum = 0x00000013,
    _EnumAndUnderlying = 0x00000014,
    _UnderlyingAndEnum = 0x00000015,
    Pointer = 0x00000016,

    OpMask = 0x0000FF00,

    PostfixIncrement = 0x00001000,
    PostfixDecrement = 0x00001100,
    PrefixIncrement = 0x00001200,
    PrefixDecrement = 0x00001300,
    UnaryPlus = 0x00001400,
    UnaryMinus = 0x00001500,
    LogicalNegation = 0x00001600,
    BitwiseComplement = 0x00001700,
    True = 0x00001800,
    False = 0x00001900,

    _Conditional = 0x00010000,
    Lifted = 0x00020000,

    Int8PostfixIncrement = Int8 | PostfixIncrement,
    Int16PostfixIncrement = Int16 | PostfixIncrement,
    Int32PostfixIncrement = Int32 | PostfixIncrement,
    Int64PostfixIncrement = Int64 | PostfixIncrement,
    UInt8PostfixIncrement = UInt8 | PostfixIncrement,
    UInt16PostfixIncrement = UInt16 | PostfixIncrement,
    UInt32PostfixIncrement = UInt32 | PostfixIncrement,
    UInt64PostfixIncrement = UInt64 | PostfixIncrement,
    Float32PostfixIncrement = Float32 | PostfixIncrement,
    Float64PostfixIncrement = Float64 | PostfixIncrement,
    EnumPostfixIncrement = Enum | PostfixIncrement,
    UserDefinedPostfixIncrement = UserDefined | PostfixIncrement,
    LiftedInt8PostfixIncrement = Lifted | Int8 | PostfixIncrement,
    LiftedInt16PostfixIncrement = Lifted | Int16 | PostfixIncrement,
    LiftedInt32PostfixIncrement = Lifted | Int32 | PostfixIncrement,
    LiftedInt64PostfixIncrement = Lifted | Int64 | PostfixIncrement,
    LiftedUInt8PostfixIncrement = Lifted | UInt8 | PostfixIncrement,
    LiftedUInt16PostfixIncrement = Lifted | UInt16 | PostfixIncrement,
    LiftedUInt32PostfixIncrement = Lifted | UInt32 | PostfixIncrement,
    LiftedUInt64PostfixIncrement = Lifted | UInt64 | PostfixIncrement,
    LiftedFloat32PostfixIncrement = Lifted | Float32 | PostfixIncrement,
    LiftedFloat64PostfixIncrement = Lifted | Float64 | PostfixIncrement,
    LiftedEnumPostfixIncrement = Lifted | Enum | PostfixIncrement,
    LiftedUserDefinedPostfixIncrement = Lifted | UserDefined | PostfixIncrement,

    Int8PrefixIncrement = Int8 | PrefixIncrement,
    Int16PrefixIncrement = Int16 | PrefixIncrement,
    Int32PrefixIncrement = Int32 | PrefixIncrement,
    Int64PrefixIncrement = Int64 | PrefixIncrement,
    UInt8PrefixIncrement = UInt8 | PrefixIncrement,
    UInt16PrefixIncrement = UInt16 | PrefixIncrement,
    UInt32PrefixIncrement = UInt32 | PrefixIncrement,
    UInt64PrefixIncrement = UInt64 | PrefixIncrement,
    Float32PrefixIncrement = Float32 | PrefixIncrement,
    Float64PrefixIncrement = Float64 | PrefixIncrement,
    EnumPrefixIncrement = Enum | PrefixIncrement,
    UserDefinedPrefixIncrement = UserDefined | PrefixIncrement,
    LiftedInt8PrefixIncrement = Lifted | Int8 | PrefixIncrement,
    LiftedInt16PrefixIncrement = Lifted | Int16 | PrefixIncrement,
    LiftedInt32PrefixIncrement = Lifted | Int32 | PrefixIncrement,
    LiftedInt64PrefixIncrement = Lifted | Int64 | PrefixIncrement,
    LiftedUInt8PrefixIncrement = Lifted | UInt8 | PrefixIncrement,
    LiftedUInt16PrefixIncrement = Lifted | UInt16 | PrefixIncrement,
    LiftedUInt32PrefixIncrement = Lifted | UInt32 | PrefixIncrement,
    LiftedUInt64PrefixIncrement = Lifted | UInt64 | PrefixIncrement,
    LiftedFloat32PrefixIncrement = Lifted | Float32 | PrefixIncrement,
    LiftedFloat64PrefixIncrement = Lifted | Float64 | PrefixIncrement,
    LiftedEnumPrefixIncrement = Lifted | Enum | PrefixIncrement,
    LiftedUserDefinedPrefixIncrement = Lifted | UserDefined | PrefixIncrement,

    Int8PostfixDecrement = Int8 | PostfixDecrement,
    Int16PostfixDecrement = Int16 | PostfixDecrement,
    Int32PostfixDecrement = Int32 | PostfixDecrement,
    Int64PostfixDecrement = Int64 | PostfixDecrement,
    UInt8PostfixDecrement = UInt8 | PostfixDecrement,
    UInt16PostfixDecrement = UInt16 | PostfixDecrement,
    UInt32PostfixDecrement = UInt32 | PostfixDecrement,
    UInt64PostfixDecrement = UInt64 | PostfixDecrement,
    Float32PostfixDecrement = Float32 | PostfixDecrement,
    Float64PostfixDecrement = Float64 | PostfixDecrement,
    EnumPostfixDecrement = Enum | PostfixDecrement,
    UserDefinedPostfixDecrement = UserDefined | PostfixDecrement,
    LiftedInt8PostfixDecrement = Lifted | Int8 | PostfixDecrement,
    LiftedInt16PostfixDecrement = Lifted | Int16 | PostfixDecrement,
    LiftedInt32PostfixDecrement = Lifted | Int32 | PostfixDecrement,
    LiftedInt64PostfixDecrement = Lifted | Int64 | PostfixDecrement,
    LiftedUInt8PostfixDecrement = Lifted | UInt8 | PostfixDecrement,
    LiftedUInt16PostfixDecrement = Lifted | UInt16 | PostfixDecrement,
    LiftedUInt32PostfixDecrement = Lifted | UInt32 | PostfixDecrement,
    LiftedUInt64PostfixDecrement = Lifted | UInt64 | PostfixDecrement,
    LiftedFloat32PostfixDecrement = Lifted | Float32 | PostfixDecrement,
    LiftedFloat64PostfixDecrement = Lifted | Float64 | PostfixDecrement,
    LiftedEnumPostfixDecrement = Lifted | Enum | PostfixDecrement,
    LiftedUserDefinedPostfixDecrement = Lifted | UserDefined | PostfixDecrement,

    Int8PrefixDecrement = Int8 | PrefixDecrement,
    Int16PrefixDecrement = Int16 | PrefixDecrement,
    Int32PrefixDecrement = Int32 | PrefixDecrement,
    Int64PrefixDecrement = Int64 | PrefixDecrement,
    UInt8PrefixDecrement = UInt8 | PrefixDecrement,
    UInt16PrefixDecrement = UInt16 | PrefixDecrement,
    UInt32PrefixDecrement = UInt32 | PrefixDecrement,
    UInt64PrefixDecrement = UInt64 | PrefixDecrement,
    Float32PrefixDecrement = Float32 | PrefixDecrement,
    Float64PrefixDecrement = Float64 | PrefixDecrement,
    EnumPrefixDecrement = Enum | PrefixDecrement,
    UserDefinedPrefixDecrement = UserDefined | PrefixDecrement,
    LiftedInt8PrefixDecrement = Lifted | Int8 | PrefixDecrement,
    LiftedInt16PrefixDecrement = Lifted | Int16 | PrefixDecrement,
    LiftedInt32PrefixDecrement = Lifted | Int32 | PrefixDecrement,
    LiftedInt64PrefixDecrement = Lifted | Int64 | PrefixDecrement,
    LiftedUInt8PrefixDecrement = Lifted | UInt8 | PrefixDecrement,
    LiftedUInt16PrefixDecrement = Lifted | UInt16 | PrefixDecrement,
    LiftedUInt32PrefixDecrement = Lifted | UInt32 | PrefixDecrement,
    LiftedUInt64PrefixDecrement = Lifted | UInt64 | PrefixDecrement,
    LiftedFloat32PrefixDecrement = Lifted | Float32 | PrefixDecrement,
    LiftedFloat64PrefixDecrement = Lifted | Float64 | PrefixDecrement,
    LiftedEnumPrefixDecrement = Lifted | Enum | PrefixDecrement,
    LiftedUserDefinedPrefixDecrement = Lifted | UserDefined | PrefixDecrement,

    Int32UnaryPlus = Int32 | UnaryPlus,
    Int64UnaryPlus = Int64 | UnaryPlus,
    UInt32UnaryPlus = UInt32 | UnaryPlus,
    UInt64UnaryPlus = UInt64 | UnaryPlus,
    Float32UnaryPlus = Float32 | UnaryPlus,
    Float64UnaryPlus = Float64 | UnaryPlus,
    UserDefinedUnaryPlus = UserDefined | UnaryPlus,
    LiftedInt32UnaryPlus = Lifted | Int32 | UnaryPlus,
    LiftedInt64UnaryPlus = Lifted | Int64 | UnaryPlus,
    LiftedUInt32UnaryPlus = Lifted | UInt32 | UnaryPlus,
    LiftedUInt64UnaryPlus = Lifted | UInt64 | UnaryPlus,
    LiftedFloat32UnaryPlus = Lifted | Float32 | UnaryPlus,
    LiftedFloat64UnaryPlus = Lifted | Float64 | UnaryPlus,
    LiftedUserDefinedUnaryPlus = Lifted | UserDefined | UnaryPlus,

    Int32UnaryMinus = Int32 | UnaryMinus,
    Int64UnaryMinus = Int64 | UnaryMinus,
    Float32UnaryMinus = Float32 | UnaryMinus,
    Float64UnaryMinus = Float64 | UnaryMinus,
    UserDefinedUnaryMinus = UserDefined | UnaryMinus,
    LiftedInt32UnaryMinus = Lifted | Int32 | UnaryMinus,
    LiftedInt64UnaryMinus = Lifted | Int64 | UnaryMinus,
    LiftedFloat32UnaryMinus = Lifted | Float32 | UnaryMinus,
    LiftedFloat64UnaryMinus = Lifted | Float64 | UnaryMinus,
    LiftedUserDefinedUnaryMinus = Lifted | UserDefined | UnaryMinus,

    BoolLogicalNegation = Bool | LogicalNegation,
    UserDefinedLogicalNegation = UserDefined | LogicalNegation,
    LiftedBoolLogicalNegation = Lifted | Bool | LogicalNegation,
    LiftedUserDefinedLogicalNegation = Lifted | UserDefined | LogicalNegation,

    Int32BitwiseComplement = Int32 | BitwiseComplement,
    Int64BitwiseComplement = Int64 | BitwiseComplement,
    UInt32BitwiseComplement = UInt32 | BitwiseComplement,
    UInt64BitwiseComplement = UInt64 | BitwiseComplement,
    EnumBitwiseComplement = Enum | BitwiseComplement,
    UserDefinedBitwiseComplement = UserDefined | BitwiseComplement,
    LiftedInt32BitwiseComplement = Lifted | Int32 | BitwiseComplement,
    LiftedInt64BitwiseComplement = Lifted | Int64 | BitwiseComplement,
    LiftedUInt32BitwiseComplement = Lifted | UInt32 | BitwiseComplement,
    LiftedUInt64BitwiseComplement = Lifted | UInt64 | BitwiseComplement,
    LiftedEnumBitwiseComplement = Lifted | Enum | BitwiseComplement,
    LiftedUserDefinedBitwiseComplement = Lifted | UserDefined | BitwiseComplement,

    UserDefinedTrue = UserDefined | True,
    UserDefinedFalse = UserDefined | False,
}
