using System;

namespace Buckle.CodeAnalysis.Binding;

[Flags]
internal enum UnaryOperatorKind : int {
    Error = 0x00000000,

    TypeMask = 0x000000FF,

    Int = 0x00000001,
    UInt = 0x00000002,
    Char = 0x00000003,
    Float32 = 0x00000004,
    Float64 = 0x00000005,
    Bool = 0x00000006,
    _Object = 0x00000007,
    _String = 0x00000008,
    _Type = 0x00000009,
    _NullableNull = 0x0000000A,
    Any = 0x0000000B,
    UserDefined = 0x0000000C,
    Enum = 0x0000000D,
    _EnumAndUnderlying = 0x0000000E,
    _UnderlyingAndEnum = 0x0000000F,

    OpMask = 0x0000FF00,

    PostfixIncrement = 0x00001000,
    PostfixDecrement = 0x00001100,
    PrefixIncrement = 0x00001200,
    PrefixDecrement = 0x00001300,
    UnaryPlus = 0x00001400,
    UnaryMinus = 0x00001500,
    LogicalNegation = 0x00001600,
    BitwiseComplement = 0x00001700,
    True = 0x00001800,
    False = 0x00001900,

    _Conditional = 0x00010000,
    Lifted = 0x00020000,

    IntPostfixIncrement = Int | PostfixIncrement,
    UIntPostfixIncrement = UInt | PostfixIncrement,
    Float32PostfixIncrement = Float32 | PostfixIncrement,
    Float64PostfixIncrement = Float64 | PostfixIncrement,
    EnumPostfixIncrement = Enum | PostfixIncrement,
    UserDefinedPostfixIncrement = UserDefined | PostfixIncrement,
    LiftedIntPostfixIncrement = Lifted | Int | PostfixIncrement,
    LiftedUIntPostfixIncrement = Lifted | UInt | PostfixIncrement,
    LiftedFloat32PostfixIncrement = Lifted | Float32 | PostfixIncrement,
    LiftedFloat64PostfixIncrement = Lifted | Float64 | PostfixIncrement,
    LiftedEnumPostfixIncrement = Lifted | Enum | PostfixIncrement,
    LiftedUserDefinedPostfixIncrement = Lifted | UserDefined | PostfixIncrement,

    IntPrefixIncrement = Int | PrefixIncrement,
    UIntPrefixIncrement = UInt | PrefixIncrement,
    Float32PrefixIncrement = Float32 | PrefixIncrement,
    Float64PrefixIncrement = Float64 | PrefixIncrement,
    EnumPrefixIncrement = Enum | PrefixIncrement,
    UserDefinedPrefixIncrement = UserDefined | PrefixIncrement,
    LiftedIntPrefixIncrement = Lifted | Int | PrefixIncrement,
    LiftedUIntPrefixIncrement = Lifted | UInt | PrefixIncrement,
    LiftedFloat32PrefixIncrement = Lifted | Float32 | PrefixIncrement,
    LiftedFloat64PrefixIncrement = Lifted | Float64 | PrefixIncrement,
    LiftedEnumPrefixIncrement = Lifted | Enum | PrefixIncrement,
    LiftedUserDefinedPrefixIncrement = Lifted | UserDefined | PrefixIncrement,

    IntPostfixDecrement = Int | PostfixDecrement,
    UIntPostfixDecrement = UInt | PostfixDecrement,
    Float32PostfixDecrement = Float32 | PostfixDecrement,
    Float64PostfixDecrement = Float64 | PostfixDecrement,
    EnumPostfixDecrement = Enum | PostfixDecrement,
    UserDefinedPostfixDecrement = UserDefined | PostfixDecrement,
    LiftedIntPostfixDecrement = Lifted | Int | PostfixDecrement,
    LiftedUIntPostfixDecrement = Lifted | UInt | PostfixDecrement,
    LiftedFloat32PostfixDecrement = Lifted | Float32 | PostfixDecrement,
    LiftedFloat64PostfixDecrement = Lifted | Float64 | PostfixDecrement,
    LiftedEnumPostfixDecrement = Lifted | Enum | PostfixDecrement,
    LiftedUserDefinedPostfixDecrement = Lifted | UserDefined | PostfixDecrement,

    IntPrefixDecrement = Int | PrefixDecrement,
    UIntPrefixDecrement = UInt | PrefixDecrement,
    Float32PrefixDecrement = Float32 | PrefixDecrement,
    Float64PrefixDecrement = Float64 | PrefixDecrement,
    EnumPrefixDecrement = Enum | PrefixDecrement,
    UserDefinedPrefixDecrement = UserDefined | PrefixDecrement,
    LiftedIntPrefixDecrement = Lifted | Int | PrefixDecrement,
    LiftedUIntPrefixDecrement = Lifted | UInt | PrefixDecrement,
    LiftedFloat32PrefixDecrement = Lifted | Float32 | PrefixDecrement,
    LiftedFloat64PrefixDecrement = Lifted | Float64 | PrefixDecrement,
    LiftedEnumPrefixDecrement = Lifted | Enum | PrefixDecrement,
    LiftedUserDefinedPrefixDecrement = Lifted | UserDefined | PrefixDecrement,

    IntUnaryPlus = Int | UnaryPlus,
    UIntUnaryPlus = UInt | UnaryPlus,
    Float32UnaryPlus = Float32 | UnaryPlus,
    Float64UnaryPlus = Float64 | UnaryPlus,
    UserDefinedUnaryPlus = UserDefined | UnaryPlus,
    LiftedIntUnaryPlus = Lifted | Int | UnaryPlus,
    LiftedUIntUnaryPlus = Lifted | UInt | UnaryPlus,
    LiftedFloat32UnaryPlus = Lifted | Float32 | UnaryPlus,
    LiftedFloat64UnaryPlus = Lifted | Float64 | UnaryPlus,
    LiftedUserDefinedUnaryPlus = Lifted | UserDefined | UnaryPlus,

    IntUnaryMinus = Int | UnaryMinus,
    Float32UnaryMinus = Float32 | UnaryMinus,
    Float64UnaryMinus = Float64 | UnaryMinus,
    UserDefinedUnaryMinus = UserDefined | UnaryMinus,
    LiftedIntUnaryMinus = Lifted | Int | UnaryMinus,
    LiftedFloat32UnaryMinus = Lifted | Float32 | UnaryMinus,
    LiftedFloat64UnaryMinus = Lifted | Float64 | UnaryMinus,
    LiftedUserDefinedUnaryMinus = Lifted | UserDefined | UnaryMinus,

    BoolLogicalNegation = Bool | LogicalNegation,
    UserDefinedLogicalNegation = UserDefined | LogicalNegation,
    LiftedBoolLogicalNegation = Lifted | Bool | LogicalNegation,
    LiftedUserDefinedLogicalNegation = Lifted | UserDefined | LogicalNegation,

    IntBitwiseComplement = Int | BitwiseComplement,
    UIntBitwiseComplement = UInt | BitwiseComplement,
    EnumBitwiseComplement = Enum | BitwiseComplement,
    UserDefinedBitwiseComplement = UserDefined | BitwiseComplement,
    LiftedIntBitwiseComplement = Lifted | Int | BitwiseComplement,
    LiftedUIntBitwiseComplement = Lifted | UInt | BitwiseComplement,
    LiftedEnumBitwiseComplement = Lifted | Enum | BitwiseComplement,
    LiftedUserDefinedBitwiseComplement = Lifted | UserDefined | BitwiseComplement,

    UserDefinedTrue = UserDefined | True,
    UserDefinedFalse = UserDefined | False,
}
