
namespace Buckle.CodeAnalysis.Syntax;

/// <summary>
/// All types of things to be found in a source file.
/// </summary>
public enum SyntaxKind : ushort {
    None = 0,
    List = GreenNode.ListKind,

    // Punctuation
    TildeToken,
    ExclamationToken,
    PercentToken,
    CaretToken,
    AmpersandToken,
    AsteriskToken,
    OpenParenToken,
    CloseParenToken,
    MinusToken,
    PlusToken,
    EqualsToken,
    OpenBraceToken,
    CloseBraceToken,
    OpenBracketToken,
    CloseBracketToken,
    PipeToken,
    SemicolonToken,
    LessThanToken,
    CommaToken,
    GreaterThanToken,
    SlashToken,
    QuestionToken,
    ColonToken,
    ColonColonToken,
    PeriodToken,
    HashToken,
    DollarToken,

    // Compound punctuation
    PipePipeToken,
    AmpersandAmpersandToken,
    MinusMinusToken,
    PlusPlusToken,
    AsteriskAsteriskToken,
    QuestionQuestionToken,
    ExclamationEqualsToken,
    EqualsEqualsToken,
    LessThanEqualsToken,
    LessThanLessThanToken,
    LessThanLessThanEqualsToken,
    GreaterThanEqualsToken,
    GreaterThanGreaterThanToken,
    GreaterThanGreaterThanEqualsToken,
    SlashEqualsToken,
    AsteriskEqualsToken,
    PipeEqualsToken,
    AmpersandEqualsToken,
    PlusEqualsToken,
    MinusEqualsToken,
    AsteriskAsteriskEqualsToken,
    CaretEqualsToken,
    PercentEqualsToken,
    QuestionQuestionEqualsToken,
    GreaterThanGreaterThanGreaterThanToken,
    GreaterThanGreaterThanGreaterThanEqualsToken,
    QuestionPeriodToken,
    QuestionOpenBracketToken,
    MinusGreaterThanToken,
    DollarQuestionToken,
    PeriodPeriodToken,
    QuestionPeriodPeriodToken,
    QuestionExclamationToken,
    QuestionExclamationEqualsToken,

    // Keywords
    TypeOfKeyword,
    NameOfKeyword,
    SizeOfKeyword,
    NullKeyword,
    NullptrKeyword,
    TrueKeyword,
    FalseKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    ForKeyword,
    DoKeyword,
    TryKeyword,
    CatchKeyword,
    FinallyKeyword,
    BreakKeyword,
    ContinueKeyword,
    ReturnKeyword,
    ConstKeyword,
    ConstexprKeyword,
    RefKeyword,
    IsKeyword,
    IsntKeyword,
    StructKeyword,
    ClassKeyword,
    NewKeyword,
    ThisKeyword,
    BaseKeyword,
    StaticKeyword,
    OperatorKeyword,
    LowlevelKeyword,
    ExtendsKeyword,
    PublicKeyword,
    PrivateKeyword,
    ProtectedKeyword,
    SealedKeyword,
    AbstractKeyword,
    VirtualKeyword,
    OverrideKeyword,
    ConstructorKeyword,
    AsKeyword,
    WhereKeyword,
    ThrowKeyword,
    PrimitiveKeyword,
    NotnullKeyword,
    UsingKeyword,
    NamespaceKeyword,
    GlobalKeyword,
    ImplicitKeyword,
    ExplicitKeyword,
    ExternKeyword,
    PinnedKeyword,
    StackAllocKeyword,
    EnumKeyword,
    ILKeyword,
    NoVerifyKeyword,
    ElifKeyword,
    EndifKeyword,
    DefineKeyword,
    UndefKeyword,
    FlagsKeyword,

    // Tokens with text
    BadToken,
    IdentifierToken,
    NumericLiteralToken,
    StringLiteralToken,
    CharacterLiteralToken,

    // Trivia
    EndOfLineTrivia,
    WhitespaceTrivia,
    SingleLineCommentTrivia,
    MultiLineCommentTrivia,
    SkippedTokensTrivia,
    BadDirectiveTrivia,
    IfDirectiveTrivia,
    ElifDirectiveTrivia,
    ElseDirectiveTrivia,
    EndIfDirectiveTrivia,
    DefineDirectiveTrivia,
    UndefDirectiveTrivia,
    DisabledTextTrivia,

    // Expressions
    ParenthesizedExpression,
    CastExpression,
    ThisExpression,
    BaseExpression,
    ThrowExpression,

    // Operator expressions
    TernaryExpression,
    BinaryExpression,
    UnaryExpression,
    IndexExpression,
    PrefixExpression,
    PostfixExpression,
    AssignmentExpression,

    // Primary expressions
    LiteralExpression,
    TypeOfExpression,
    NameOfExpression,
    SizeOfExpression,
    CallExpression,
    ReferenceExpression,
    MemberAccessExpression,
    ObjectCreationExpression,
    ArrayCreationExpression,
    CascadeListExpression,
    CascadeExpression,
    StackAllocExpression,
    ImplicitEnumFieldExpression,

    // Statements
    EmptyStatement,
    BlockStatement,
    InlineILStatement,
    ILInstruction,
    ExpressionStatement,
    LocalDeclarationStatement,
    LocalFunctionStatement,

    // Jump statements
    BreakStatement,
    ContinueStatement,
    ReturnStatement,
    WhileStatement,
    DoWhileStatement,
    ForStatement,

    // Checked statements
    IfStatement,
    ElseClause,
    TryStatement,
    CatchClause,
    FinallyClause,

    // Directives
    UsingDirective,

    // Declarations
    CompilationUnit,
    GlobalStatement,
    NamespaceDeclaration,
    FileScopedNamespaceDeclaration,
    VariableDeclaration,
    EqualsValueClause,
    StructDeclaration,
    ClassDeclaration,
    EnumDeclaration,
    EnumMemberDeclaration,
    FieldDeclaration,
    MethodDeclaration,
    ConstructorDeclaration,
    ConstructorInitializer,
    OperatorDeclaration,
    ConversionDeclaration,

    // Names
    IdentifierName,
    TemplateName,
    QualifiedName,
    AliasQualifiedName,
    EmptyName,
    ArrayType,
    NonNullableType,
    PointerType,
    FunctionPointerType,
    ReferenceType,
    BaseType,
    NameEquals,

    // Lists
    Argument,
    OmittedArgument,
    OmittedArgumentToken,
    ArgumentList,
    BracketedArgumentList,
    Parameter,
    ParameterList,
    FunctionPointerParameter,
    FunctionPointerParameterList,
    ArrayRankSpecifier,
    TemplateParameterList,
    TemplateArgumentList,
    Attribute,
    AttributeList,
    TemplateConstraintClause,
    TemplateExtendsConstraintClause,
    TemplateIsConstraintClause,
    TemplateConstraintClauseList,
    InitializerListExpression,
    KeyValuePair,
    InitializerDictionaryExpression,

    // Other
    EndOfFileToken,
    EndOfDirectiveToken,
}
