
namespace Buckle.CodeAnalysis.Syntax;

/// <summary>
/// All types of things to be found in a source file.
/// </summary>
public enum SyntaxKind : ushort {
    // ! Order matters (see SyntaxFacts)
    None = 0,
    List = GreenNode.ListKind,

    // Punctuation
    TildeToken,
    ExclamationToken,
    PercentToken,
    CaretToken,
    AmpersandToken,
    AsteriskToken,
    OpenParenToken,
    CloseParenToken,
    MinusToken,
    PlusToken,
    EqualsToken,
    OpenBraceToken,
    CloseBraceToken,
    OpenBracketToken,
    CloseBracketToken,
    PipeToken,
    SemicolonToken,
    LessThanToken,
    CommaToken,
    GreaterThanToken,
    SlashToken,
    QuestionToken,
    ColonToken,
    ColonColonToken,
    PeriodToken,
    HashToken,
    DollarToken,

    // Compound punctuation
    PipePipeToken,
    AmpersandAmpersandToken,
    MinusMinusToken,
    PlusPlusToken,
    AsteriskAsteriskToken,
    QuestionQuestionToken,
    ExclamationEqualsToken,
    ExclamationExclamationToken,
    EqualsEqualsToken,
    LessThanEqualsToken,
    LessThanLessThanToken,
    LessThanLessThanEqualsToken,
    GreaterThanEqualsToken,
    GreaterThanGreaterThanToken,
    GreaterThanGreaterThanEqualsToken,
    SlashEqualsToken,
    AsteriskEqualsToken,
    PipeEqualsToken,
    AmpersandEqualsToken,
    PlusEqualsToken,
    MinusEqualsToken,
    AsteriskAsteriskEqualsToken,
    CaretEqualsToken,
    PercentEqualsToken,
    QuestionQuestionEqualsToken,
    GreaterThanGreaterThanGreaterThanToken,
    GreaterThanGreaterThanGreaterThanEqualsToken,
    QuestionPeriodToken,
    QuestionOpenBracketToken,
    MinusGreaterThanToken,
    DollarQuestionToken,
    PeriodPeriodToken,
    QuestionPeriodPeriodToken,
    QuestionExclamationToken,
    QuestionExclamationEqualsToken,
    SlashBackslashToken,
    SlashBackslashEqualsToken,
    BackslashSlashToken,
    BackslashSlashEqualsToken,
    GreaterThanLessThanToken,
    GreaterThanLessThanEqualsToken,
    EqualsGreaterThanToken,

    // Tokens with text
    BadToken,
    IdentifierToken,
    NumericLiteralToken,
    StringLiteralToken,
    CStringLiteralToken,
    CWStringLiteralToken,
    CharacterLiteralToken,
    ExtendedLiteralToken,
    InterpolatedStringLiteralToken,

    // Keywords
    TypeOfKeyword,
    NameOfKeyword,
    SizeOfKeyword,
    NullKeyword,
    NullptrKeyword,
    TrueKeyword,
    FalseKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    ForKeyword,
    DoKeyword,
    TryKeyword,
    CatchKeyword,
    FinallyKeyword,
    BreakKeyword,
    ContinueKeyword,
    ReturnKeyword,
    ConstKeyword,
    ConstexprKeyword,
    RefKeyword,
    IsKeyword,
    IsntKeyword,
    StructKeyword,
    ClassKeyword,
    NewKeyword,
    ThisKeyword,
    BaseKeyword,
    StaticKeyword,
    OperatorKeyword,
    LiteralKeyword,
    LowlevelKeyword,
    ExtendsKeyword,
    PublicKeyword,
    PrivateKeyword,
    ProtectedKeyword,
    SealedKeyword,
    AbstractKeyword,
    VirtualKeyword,
    OverrideKeyword,
    ConstructorKeyword,
    FinalizerKeyword,
    DestructorKeyword,
    AsKeyword,
    WhereKeyword,
    ThrowKeyword,
    PrimitiveKeyword,
    NotnullKeyword,
    UsingKeyword,
    NamespaceKeyword,
    GlobalKeyword,
    ImplicitKeyword,
    ExplicitKeyword,
    ExternKeyword,
    PinnedKeyword,
    StackAllocKeyword,
    CaseKeyword,
    DefaultKeyword,
    SwitchKeyword,
    GotoKeyword,
    EnumKeyword,
    ILKeyword,
    NoVerifyKeyword,
    ElifKeyword,
    EndifKeyword,
    DefineKeyword,
    UndefKeyword,
    FlagsKeyword,
    InKeyword,
    OutKeyword,
    UnionKeyword,
    WithKeyword,
    DeferKeyword,
    UnreachableKeyword,
    ScopedKeyword,
    FinalKeyword,
    PackedKeyword,
    ReverseKeyword,
    StateKeyword,
    HandleKeyword,

    // Trivia
    EndOfLineTrivia,
    WhitespaceTrivia,
    SingleLineCommentTrivia,
    MultiLineCommentTrivia,
    SkippedTokensTrivia,
    BadDirectiveTrivia,
    IfDirectiveTrivia,
    ElifDirectiveTrivia,
    ElseDirectiveTrivia,
    EndIfDirectiveTrivia,
    DefineDirectiveTrivia,
    UndefDirectiveTrivia,
    DisabledTextTrivia,
    ShebangDirectiveTrivia,
    PreprocessingMessageTrivia,
    HandleDirectiveTrivia,

    // Expressions
    ParenthesizedExpression,
    CastExpression,
    BitCastExpression,
    ThisExpression,
    BaseExpression,
    ThrowExpression,
    DeclarationExpression,
    WithExpression,

    // Operator expressions
    TernaryExpression,
    BinaryExpression,
    UnaryExpression,
    IndexExpression,
    PrefixExpression,
    PostfixExpression,
    AssignmentExpression,
    IsPatternExpression,
    ClampExpression,
    DeclarationPattern,

    // Primary expressions
    LiteralExpression,
    ExtendedLiteralExpression,
    TypeOfExpression,
    NameOfExpression,
    SizeOfExpression,
    CallExpression,
    ReferenceExpression,
    MemberAccessExpression,
    ObjectCreationExpression,
    ArrayCreationExpression,
    CascadeListExpression,
    CascadeExpression,
    StackAllocExpression,
    ImplicitEnumFieldExpression,
    InterpolatedStringExpression,
    ParenthesizedLambdaExpression,
    SimpleLambdaExpression,
    TupleExpression,
    InterpolatedStringText,
    Interpolation,
    InterpolatedStringStartToken,
    InterpolatedStringEndToken,

    // Statements
    EmptyStatement,
    BlockStatement,
    InlineILStatement,
    ExpressionStatement,
    ScopedStatement,
    WithStatement,
    LocalDeclarationStatement,
    LocalFunctionStatement,

    // Control flow statements
    BreakStatement,
    ContinueStatement,
    ReturnStatement,
    WhileStatement,
    DoWhileStatement,
    ForStatement,
    ForEachStatement,
    IfStatement,
    TryStatement,
    SwitchStatement,
    GotoStatement,
    DeferStatement,
    UnreachableStatement,
    NullBindingStatement,

    // Statement Parts
    ILInstruction,
    SwitchSection,
    CaseSwitchLabel,
    DefaultSwitchLabel,
    MultiCaseSwitchLabel,
    CatchClause,
    FinallyClause,
    ElseClause,

    // Directives
    UsingDirective,

    // Declarations
    CompilationUnit,
    GlobalStatement,
    NamespaceDeclaration,
    FileScopedNamespaceDeclaration,
    VariableDeclaration,
    EqualsValueClause,
    StructDeclaration,
    PackedArgument,
    ClassDeclaration,
    FileScopedClassDeclaration,
    UnionDeclaration,
    EnumDeclaration,
    EnumMemberDeclaration,
    FieldDeclaration,
    MethodDeclaration,
    ReverseClause,
    ConstructorDeclaration,
    ConstructorInitializer,
    DestructorDeclaration,
    FinalizerDeclaration,
    OperatorDeclaration,
    LiteralOperatorDeclaration,
    ConversionDeclaration,

    // Names
    IdentifierName,
    TemplateName,
    QualifiedName,
    AliasQualifiedName,
    EmptyName,
    ArrayType,
    NonNullableType,
    NullableType,
    PointerType,
    FunctionPointerType,
    FunctionType,
    ReferenceType,
    TupleType,
    TupleElement,
    BaseType,
    NameEquals,

    // Lists
    Argument,
    OmittedArgument,
    OmittedArgumentToken,
    ArgumentList,
    BracketedArgumentList,
    Parameter,
    ParameterList,
    FunctionPointerParameter,
    FunctionPointerParameterList,
    ArrayRankSpecifier,
    TemplateParameterList,
    TemplateArgumentList,
    Attribute,
    AttributeList,
    TemplateConstraintClause,
    TemplateExtendsConstraintClause,
    TemplateIsConstraintClause,
    TemplateConstraintClauseList,
    InitializerListExpression,
    KeyValuePair,
    InitializerDictionaryExpression,

    // Other
    EndOfFileToken,
    EndOfDirectiveToken,
}
