
namespace Buckle.CodeAnalysis;

public enum OperationKind : int
{
    None = 0,
    Invalid = 1,
    Block = 2,
    VariableDeclaration = 3,
    Loop = 4,
    Branch = 5,
    Empty = 6,
    Return = 7,
    Using = 8,
    ExpressionStatement = 9,
    LocalFunction = 10,
    Literal = 11,
    Conversion = 12,
    Invocation = 13,
    ArrayElementReference = 14,
    LocalReference = 15,
    ParameterRefKinds = 16,
    FieldReference = 17,
    MethodReference = 18,
    Unary = 19,
    UnaryOperator = 20,
    Binary = 21,
    BinaryOperator = 22,
    Conditional = 23,
    Coalesce = 24,
    ObjectCreation = 25,
    TemplateParameterObjectCreation = 26,
    ArrayCreation = 27,
    InstanceReference = 28,
    IsType = 29,
    SimpleAssignment = 30,
    CompoundAssignment = 31,
    Parenthesized = 32,
    ConditionalAccess = 33,
    ConditionalAccessInstance = 34,
    MemberInitializer = 35,
    CollectionElementInitializer = 36,
    NameOf = 37,
    TypeOf = 38,
    Increment = 39,
    Decrement = 40,
    DeclarationExpression = 41,
    OmittedArgument = 42,
    FieldInitializer = 43,
    VariableInitializer = 44,
    ParameterInitializer = 45,
    ArrayInitializer = 46,
    Argument = 47,
    MethodBody = 48,
    ConstructorBody = 49,
    IsNull = 50,
    CoalesceAssignment = 51,
    CollectionExpression = 52,
}
