
namespace Buckle.CodeAnalysis.Binding;

internal enum ConversionKind : byte {
    None,
    DefaultLiteral,
    NullLiteral,
    Identity,
    Implicit,
    ImplicitNullable,
    ImplicitReference,
    ImplicitConstant,
    ImplicitUserDefined,
    ImplicitPointerToVoid,
    ImplicitNullToPointer,
    ImplicitEnum,
    ImplicitNumeric,
    ImplicitTupleLiteral,
    AnyBoxing,
    Explicit,
    ExplicitNullable,
    ExplicitReference,
    ExplicitUserDefined,
    ExplicitPointerToPointer,
    ExplicitIntegerToPointer,
    ExplicitPointerToInteger,
    ExplicitEnum,
    ExplicitNumeric,
    AnyUnboxing,
    ListExpression,
    MethodGroup,
    ObjectCreation,
    ConditionalExpression,
    Deconstruction,
}
